language: python
python:
- '2.7'
install:
- python setup.py install
script:
- python setup.py install
deploy:
  provider: pypi
  user: SimplicityGuy
  password:
    secure: Fw92GXFg7DyJ7bYYagqz2u+HSbsWjMDFWxvKrAYcvh+ndd4uJlr1KT+xOYg/4v7Bz7pZV6AWJV0Mpuc57dYVAYK5ylfw6ITCFO8SmGK8XTelOD0LtLql5d1TssFpxDfLKf+C3hLKojx7gOnUtt0X4gpg2jkKaAvhnzsc9b677QTimjRJunPJG7gLzC6tKbT5gxy6wOe06rDxO9nWDYdTOXt0FjXcGsAzHFIglavM0MhowrG4kuHdRZQlxfwqp5yYVRu+xBP6a0XVl0zCYuvr6kxRdVEVgfHaTGdt5+q3kV7CFZgMnj0esSA829OdeNhIWbCW32ErZBo/Rk612FjNZKjg5hY7qZEf/uUHn6tqLKNEneVDzbYSYaks0UhbAWIR4RRi2MFeM00Hzfmy/qtv67aIAMBP1oQjCjnwkxQibWG5/p81sIVXW0yV00KaMX5SomfoGJN7NaaafUVihjv2u5tSbPRgypcmb+/svKkn0Dm1gUOEmurY/FIwkGzw7cba9UeJZuR4Ra1VhwDkRAw+yNsQRZSdql40flnaZOL8NhwRmadH7vGG4g4qbSokMpK07RlUt9/iO8I/xHWt/qAMYjyY4WDtoe9iyrCGuXoS/F6m/aQT3I4oDCzp3HI09Vt7fwvhODE/kjfGQydkaYsoQI5aFCWsAs1EIOuv8LJRGks=
  on:
    tags: true
    branch: master
